name: "CrossOver"
rng_seed        : 42
num_gpu         : 1
base_dir        : "/drive/dumps/multimodal-spaces/"
exp_dir         : ""
mode            : "train"
naming_keywords : ['task', 'time']

resume : False

logger :
  name : "wandb"
  entity : "multimodal-spaces"

  
data :
  sources     : ['Scannet']
  process_dir : ${base_dir}/preprocess_feats
  
  Scannet:
    base_dir         : /drive/datasets/Scannet
    shape_dir        : /drive/datasets/Shapenet/ShapeNetCore.v2
    process_dir      : ${data.process_dir}/Scannet/
    chunked_dir      : ${data.process_dir}/Scannet/objects_chunked/
    processor1D      : Scannet1DProcessor
    processor2D      : Scannet2DProcessor
    processor3D      : Scannet3DProcessor
    mesh_subfix      : _vh_clean_2.labels.ply
    seg_subfix       : _vh_clean_2.0.010000.segs.json
    aggre_subfix     : _vh_clean.aggregation.json
    avail_modalities : ['point', 'cad', 'rgb', 'referral']
    max_object_len   : 150
    voxel_size       : 0.02
  
  Scan3R:
    base_dir       : /drive/datasets/Scan3R/
    process_dir    : ${data.process_dir}/Scan3R/
    chunked_dir    : ${data.process_dir}/Scan3R/objects_chunked/
    processor3D    : Scan3R3DProcessor
    processor2D    : Scan3R2DProcessor
    processor1D    : Scan3R1DProcessor
    label_filename : labels.instances.align.annotated.v2.ply
    avail_modalities : ['point', 'cad', 'rgb', 'referral']
    max_object_len : 150
    voxel_size     : 0.02

task: 
  name       : SceneLevelGrounding 
  SceneLevelGrounding :
    modalities  : ['rgb', 'point', 'cad', 'referral']
    train       : [Scannet, Scan3R]
    val         : [Scannet, Scan3R]

trainer: GroundingTrainer

model:
  name: SceneLevelEncoder
  point:
    embed_dim : 384
  cad:
    embed_dim : 384
  image:
    embed_dim : 1536
  referral:
    embed_dim : 768

  out_dim       : 768
  loss          : SceneWiseContrastiveLoss
  base_modality : 'rgb'

dataloader:
  batch_size  : 16
  num_workers : 6

eval:
  train:
    name: GroundingEval
  val:
    name: GroundingEval
  save: False

solver:
  gradient_accumulation_steps: 1
  epochs_per_save: 20
  epochs_per_eval: 1
  lr: 1e-3
  grad_norm: 5.0
  epochs: 300
  optim:
    name: 'AdamW'
    args:
      betas: [0.9, 0.98]
  sched:
    name: 'warmup_cosine'
    args:
      warmup_steps: 200
      minimum_ratio: 0.1